### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by yuriteixeira** [adyenpayments/client-side-encryption#13]
Where are the tags for each release?

**Comment by xslim** [comment]
There are different releases for different platforms. Tags will make sense if we will split the repository.
What kind of platforms / sdks are you interested in?

**Comment by xslim** [comment]
New iOS repository moved to https://github.com/Adyen/CSE-iOS

**Comment by xslim** [comment]
Tag 1.0.0 created as well.
