### ISSUE TITLE
binary libcrypto on iOS ?

### ISSUE THREAD

**Issue by Diwann** [adyenpayments/client-side-encryption#15]
The libcrypto.a file you include in your lib lacks arm64 support. 
Do we need to use this version of the library or can't we include directly the source library from here : 
https://github.com/x2on/OpenSSL-for-iPhone ?

**Comment by seb0zz** [comment]
Any feedback on this one? Would be awesome!

**Comment by ceichinger** [comment]
+1

**Comment by xslim** [comment]
We do not use the OpenSSL anymore, please check the new version of our client side encryption.

**Comment by seb0zz** [comment]
https://github.com/adyenpayments/client-side-encryption/tree/master/ios/AdyenClientsideEncryptionNew

Just in case anyone is wondering where to find the new version...

**Comment by xslim** [comment]
Please note - repository moved to https://github.com/Adyen/CSE-iOS

**Comment by Diwann** [comment]
Indeed : interesting to know! 
How long will you still support the previous encryption version?

**Comment by Diwann** [comment]
"ADYEncription" ? seriously ?

**Comment by xslim** [comment]
Thank you for reporting the typo. Fixed.
As of support for previous version - the encryption algorithm is the same - `AES-CCM`, only the implementation is different.
