### ISSUE TITLE
Problems with 	iOS client side encryption without OpenSSL

### ISSUE THREAD

**Issue by marciok** [adyenpayments/client-side-encryption#18]
It doesn't work.

When I generate a token using the new API 
```objective-c
[ADYEncrypter encrypt:requestData publicKeyInHex:AdyenPublicKey];
```
I get:  "..validation 174 Unable to decrypt data"

Encrypting with the older version works.

Hint: We are having the same issue with Android.

**Comment by xslim** [comment]
Hey @marciok ! Could you please check if this issue is still occurring with latest version? 
I did a bugfix in 325cb15a59f52c05ffeb3bf84795621dcb953727

**Comment by marciok** [comment]
It's fixed thanks !

**Comment by xslim** [comment]
Please note - repository moved to https://github.com/Adyen/CSE-iOS
